services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/


  mochiapi:
    image: mochiapi
    build:
      context: .
      dockerfile: ./src/vm.MochiCore.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=db;Port=5432;Database=db;User Id=admin;Password=admin1234;"
    
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  postgres_data:
